---
- hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Ensure Ansible dependencies are installed (CentOS 6).
      yum:
        name: libselinux-python
        state: present
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version | int == 6

  roles:
    - role: geerlingguy.nfs

    - role: geerlingguy.packer_rhel
      when: ansible_os_family == 'RedHat'

    - role: geerlingguy.packer-debian
      when: ansible_os_family == 'Debian'

  tasks:
    - include_vars: packages.yml
    - include_vars: services.yml

    - name: Upgrade all packages.
      yum: name=* state=latest
      when: ansible_os_family == 'RedHat'

    - name: Upgrade all packages.
      apt: name=* state=latest
      when: ansible_os_family == 'Debian'

    - name: Merge packages with common.
      set_fact:
        debian_all_packages: "{{ common_packages + debian_packages }}"

    - name: Merge packages with common.
      set_fact:
        redhat_all_packages: "{{ common_packages + redhat_packages }}"

    - name: Install some helpful utilities.
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ debian_all_packages }}"
      when: ansible_os_family == 'Debian'

    - name: Install some helpful utilities.
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ redhat_all_packages }}"
      when: ansible_os_family == 'RedHat'

    - name: Install services.
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items: "{{ debian_services }}"
      when: ansible_os_family == 'Debian'

    - name: Install services.
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items: "{{ redhat_services }}"
      when: ansible_os_family == 'RedHat'

    - name: Ensure SELinux is disabled.
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: SELINUX=disabled
      when: ansible_os_family == 'RedHat'

    - name: Setting swappiness.
      lineinfile:
        path: /etc/sysctl.conf
        line: 'vm.swappiness=0'
      when: ansible_os_family == 'RedHat'

    - name: Setting overcommit memory.
      lineinfile:
        path: /etc/sysctl.conf
        line: 'vm.overcommit_memory=1'
      when: ansible_os_family == 'RedHat'

    - name: Remove touch from rclocal.
      lineinfile:
        state: absent
        path: /etc/rc.local
        line: 'touch /var/lock/subsys/local'
      when: ansible_os_family == 'RedHat'

    - name: Handling Transparent Huge pages defrag.
      lineinfile:
        path: /etc/rc.local
        line: 'echo never > /sys/kernel/mm/transparent_hugepage/defrag'
      when: ansible_os_family == 'RedHat'

    - name: Handling Transparent Huge pages enabling.
      lineinfile:
        path: /etc/rc.local
        line: 'echo never > /sys/kernel/mm/transparent_hugepage/enabled'
      when: ansible_os_family == 'RedHat'

    - name: Add back touch to rclocal.
      lineinfile:
        state: present
        path: /etc/rc.local
        line: 'touch /var/lock/subsys/local'
      when: ansible_os_family == 'RedHat'

    - name: Making rclocal executable.
      file:
        path: /etc/rc.d/rc.local
        mode: "u=rwx,g=rx,o=rx"

