---
- hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Ensure Ansible dependencies are installed (CentOS 6).
      yum:
        name: libselinux-python
        state: present
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version | int == 6

  roles:
    - role: geerlingguy.nfs

    - role: geerlingguy.packer_rhel
      when: ansible_os_family == 'RedHat'

    - role: geerlingguy.packer-debian
      when: ansible_os_family == 'Debian'

  tasks:
    - include_vars: packages.yml
    - include_vars: services.yml

    - name: Merge Debian packages with common.
      set_fact:
        debian_all_packages: "{{ common_packages + debian_packages }}"

    - name: Merge RedHat packages with common.
      set_fact:
        redhat_all_packages: "{{ common_packages + redhat_packages }}"

    - name: Install some helpful utilities for Debian.
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ debian_all_packages }}"
      when: ansible_os_family == 'Debian'

    - name: Install some helpful utilities for RedHat.
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ redhat_all_packages }}"
      when: ansible_os_family == 'RedHat'

    - name: Install services for Debian.
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items: "{{ debian_services }}"
      when: ansible_os_family == 'Debian'

    - name: Install services for RedHat.
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items: "{{ redhat_services }}"
      when: ansible_os_family == 'RedHat'
